// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import type { PrismaConfig } from 'prisma';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations'

    // seed: 'tsx prisma/seed.ts'
    // tsx を利用していないので見送り
  },
  datasource: {
    // url: process.env['DATABASE_URL'] ?? ''
    // tsconfig をいじる必要あり

    url: env('DATABASE_URL')
  }
}) satisfies PrismaConfig;
